### ISSUE TITLE
Push to PR branch?

### ISSUE THREAD

**Issue by colemanw** [demeritcowboy/civicrm-regen#1]
This action is great!
The icing on the cake would be the ability to automatically create a commit & push to the PR.

**Comment by demeritcowboy** [comment]
I like your thinking but would like to put on hold because:

1. A github action script can access the repo it runs in without too much trouble, but accessing a different repo in order to push to their existing branch (in the owner's `civicrm-core` fork) requires a higher level of authentication and would mean the end-user of this would need to set up an access token for their user account and add it into the repository settings secrets within the fork. It's doable but is an extra few steps that makes this less appealing.
   * Theoretically, it would also require vigilance then by the fork owner if I or someone else who has access to the original regen script updates it and the owner then blindly pulls from "upstream" into their fork, since that could sneak in something that steals the credential. Obviously I wouldn't (knowingly) do that but you can see it starts to get tricky. (I'm still new to trying to grasp all the pitfalls here.)

2. A longer-term goal is to eliminate the need for civicrm_generated at all. I put this up since my headspace was already in github actions for other things and this is also useful to me in the interim since it's awkward to run regen on windows.

**Comment by colemanw** [comment]
I get point `#2` and that probably makes `#1` moot, but out of curiosity if this action lived in the `civicrm-core` repo then everyone would have it in their fork right? And it could push to that same fork to add the file to their PR?

**Comment by demeritcowboy** [comment]
Good thinking! And then that would also mean you don't have to paste the PR link into the dropdown - the first built-in field in the dropdown is already a branch selector (would just have to be a little careful about if someone with admin rights to the real civicrm-core accidentally runs it there and chooses master by accident - I suppose it's easy to revert but the script could have some safety checks). I will try this out later.

**Comment by demeritcowboy** [comment]
https://github.com/civicrm/civicrm-core/pull/20680
